# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cpu-int-app-svc
spec:
  selector:
    app: cpu-int-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

